<a href="https://colab.research.google.com/github/Niamh2602/test/blob/main/Project_test_(Accommodation%20only).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
import io
import pandas as pd
import folium
import gc


data = files.upload()

Saving Accommodation.csv to Accommodation.csv
Saving Activities.csv to Activities.csv

In [2]:
Accommodation = pd.read_csv('Accommodation.csv', header = 0, index_col= None)
Activities = pd.read_csv('Activities.csv', header = 0, index_col= None)

In [3]:
Accommodation.head()

,Name,Url,Telephone,Longitude,Latitude,AddressRegion,AddressLocality,AddressCountry,Tags
0,Bramble Rock,http://www.bramblerock.com,+353(0)40445075,-6.291733,53.009756,Wicklow,Glendalough,Republic of Ireland,B&B
1,The Davenport,http://www.instagram.com/thedavenportdublin/,+353(0)16073500,-6.250031,53.341665,Dublin,Dublin City,Republic of Ireland,"Hotel,Covid Safety Charter"
2,Townsend House,http://www.townsendhouse-guesthouse.com,+353(0)579121276,-7.909500,53.098816,Offaly,Birr,Republic of Ireland,"Guesthouse,Covid Safety Charter"
3,River's Edge,http://www.riversedge.ie,3.5367E+11,-9.783882,52.106485,Kerry,Killorglin,Ireland,"B&B,B&B Ireland"
4,Amber Springs Hotel & Health Spa,https://www.ambersprings.ie/,+353(0)539484000,-6.290339,52.668124,Wexford,Gorey,Republic of Ireland,"Hotel,Covid Safety Charter,Stay and Spend"

In [4]:
Accommodation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2773 entries, 0 to 2772
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             2773 non-null   object
 1   Url              2591 non-null   object
 2   Telephone        2768 non-null   object
 3   Longitude        2773 non-null   float64
 4   Latitude         2773 non-null   float64
 5   AddressRegion    2773 non-null   object
 6   AddressLocality  2631 non-null   object
 7   AddressCountry   2773 non-null   object
 8   Tags             2773 non-null   object
dtypes: float64(2), object(7)
memory usage: 195.1+ KB

In [5]:
Accommodation.isnull().sum()

Name                 0
Url                182
Telephone            5
Longitude            0
Latitude             0
AddressRegion        0
AddressLocality    142
AddressCountry       0
Tags                 0
dtype: int64

In [6]:
Activities.head()

,Name,Url,Telephone,Longitude,Latitude,AddressRegion,AddressLocality,AddressCountry,Tags
0,The Restaurant at the Abbey Hotel,http://www.abbeyhotel.ie/food-and-wine.html,353907000000,-8.193639,53.624876,Roscommon,NaN,Ireland,"Food and Drink,Restaurant"
1,Café Nutshell,https://www.facebook.com/cafenutshell/,35351422777,-6.944210,52.395136,Wexford,New Ross,Republic of Ireland,"Covid Safety Charter,Food and Drink,Restaurant..."
2,Guided Walking Tour of Sligo,NaN,NaN,-8.477043,54.268771,Sligo,Sligo Town,Republic of Ireland,"Walking,Activity Operator,Tour"
3,The Italian Kitchen,http://theitaliankitchen.ie,+353(0)18711255,-6.218041,53.411898,Dublin,Clonshaugh,Ireland,"Food and Drink,Restaurant"
4,Brasserie on the Corner,https://brasseriegalway.com,35391530333,-9.052901,53.274658,Galway,NaN,Ireland,"Covid Safety Charter,Food and Drink,Restaurant"

In [7]:
Activities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6318 entries, 0 to 6317
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             6318 non-null   object
 1   Url              5893 non-null   object
 2   Telephone        5743 non-null   object
 3   Longitude        6318 non-null   float64
 4   Latitude         6318 non-null   float64
 5   AddressRegion    6314 non-null   object
 6   AddressLocality  5375 non-null   object
 7   AddressCountry   6318 non-null   object
 8   Tags             6236 non-null   object
dtypes: float64(2), object(7)
memory usage: 444.4+ KB

In [8]:
Activities.isnull().sum()

Name                 0
Url                425
Telephone          575
Longitude            0
Latitude             0
AddressRegion        4
AddressLocality    943
AddressCountry       0
Tags                82
dtype: int64

In [9]:
Accommodation['File_Type'] = "Accom."
print(Accommodation)

                                  Name  \
0                         Bramble Rock
1                        The Davenport
2                       Townsend House
3                         River's Edge
4     Amber Springs Hotel & Health Spa
...                                ...
2768        The Red Door Country House
2769                   The Savoy Hotel
2770                  Dunmanus Cottage
2771           Travelodge Cork Airport
2772             Victoria Towers Hotel

                                               Url         Telephone  \
0                       http://www.bramblerock.com   +353(0)40445075
1     http://www.instagram.com/thedavenportdublin/   +353(0)16073500
2          http://www.townsendhouse-guesthouse.com  +353(0)579121276
3                         http://www.riversedge.ie        3.5367E+11
4                     https://www.ambersprings.ie/  +353(0)539484000
...                                            ...               ...
2768     https://www.facebook.com/TheRedDoorFahan/  +353(0)749360289
2769                 http://www.savoylimerick.com/   +353(0)61448700
2770                    https://dunmanuscottage.ie  +353(0)214381634
2771                      http://www.travelodge.ie  +353(0)214310722
2772          https://www.victoriahotelgalway.com/   +353(0)91567433

      Longitude   Latitude AddressRegion AddressLocality       AddressCountry  \
0     -6.291733  53.009756       Wicklow     Glendalough  Republic of Ireland
1     -6.250031  53.341665        Dublin     Dublin City  Republic of Ireland
2     -7.909500  53.098816        Offaly            Birr  Republic of Ireland
3     -9.783882  52.106485         Kerry      Killorglin              Ireland
4     -6.290339  52.668124       Wexford           Gorey  Republic of Ireland
...         ...        ...           ...             ...                  ...
2768  -7.466433  55.085032       Donegal       Inishowen  Republic of Ireland
2769  -8.629061  52.663152      Limerick   Limerick City  Republic of Ireland
2770  -9.542522  51.602650          Cork          Durrus  Republic of Ireland
2771  -8.470095  51.872450          Cork       Cork City  Republic of Ireland
2772  -9.047777  53.273056        Galway     Galway City  Republic of Ireland

                                                  Tags File_Type
0                                                  B&B    Accom.
1                           Hotel,Covid Safety Charter    Accom.
2                      Guesthouse,Covid Safety Charter    Accom.
3                                      B&B,B&B Ireland    Accom.
4            Hotel,Covid Safety Charter,Stay and Spend    Accom.
...                                                ...       ...
2768         B&B,Covid Safety Charter,Welcome Standard    Accom.
2769                        Hotel,Covid Safety Charter    Accom.
2770  Self Catering Accommodation,Covid Safety Charter    Accom.
2771                        Hotel,Covid Safety Charter    Accom.
2772                        Hotel,Covid Safety Charter    Accom.

[2773 rows x 10 columns]

In [10]:
Activities['File_Type'] = "Act."
print(Activities)

                                        Name  \
0          The Restaurant at the Abbey Hotel
1                              Café Nutshell
2               Guided Walking Tour of Sligo
3                        The Italian Kitchen
4                    Brasserie on the Corner
...                                      ...
6313                          The Marine Bar
6314                 The West End Cliff Walk
6315  The Workhouse Famine & Heritage Centre
6316   Walking Hiking Tours - JAQUIER Lilian
6317                Youghal Clock Gate Tower

                                                    Url         Telephone  \
0           http://www.abbeyhotel.ie/food-and-wine.html      353907000000
1                https://www.facebook.com/cafenutshell/       35351422777
2                                                   NaN               NaN
3                           http://theitaliankitchen.ie   +353(0)18711255
4                           https://brasseriegalway.com       35391530333
...                                                 ...               ...
6313                                http://marinebar.ie      +35358462520
6314                                                NaN  +353(0)749121160
6315  http://www.dunfanaghy.info/places/The-Workhous...     +353749136540
6316  https://www.facebook.com/pages/Escapades-natur...  +353(0)857481764
6317                        https://youghalclockgate.ie       +3532420769

      Longitude   Latitude AddressRegion AddressLocality       AddressCountry  \
0     -8.193639  53.624876     Roscommon             NaN              Ireland
1     -6.944210  52.395136       Wexford        New Ross  Republic of Ireland
2     -8.477043  54.268771         Sligo      Sligo Town  Republic of Ireland
3     -6.218041  53.411898        Dublin      Clonshaugh              Ireland
4     -9.052901  53.274658        Galway             NaN              Ireland
...         ...        ...           ...             ...                  ...
6313  -7.659723  52.041345     Waterford            Ring  Republic of Ireland
6314  -8.274541  54.479625       Donegal        Bundoran  Republic of Ireland
6315  -7.976993  55.179878       Donegal      Dunfanaghy  Republic of Ireland
6316 -10.021117  53.489293        Galway         Clifden  Republic of Ireland
6317  -7.846767  51.952759          Cork         Youghal  Republic of Ireland

                                                   Tags File_Type
0                             Food and Drink,Restaurant      Act.
1     Covid Safety Charter,Food and Drink,Restaurant...      Act.
2                        Walking,Activity Operator,Tour      Act.
3                             Food and Drink,Restaurant      Act.
4        Covid Safety Charter,Food and Drink,Restaurant      Act.
...                                                 ...       ...
6313             Food and Drink,Restaurant,Pubs and Bar      Act.
6314                                            Walking      Act.
6315         Museums and Attraction,Cafe,Food and Drink      Act.
6316                     Walking,Activity Operator,Tour      Act.
6317  Covid Safety Charter,Historic Houses and Castl...      Act.

[6318 rows x 10 columns]

In [11]:
pd.concat([Accommodation,Activities])

,Name,Url,Telephone,Longitude,Latitude,AddressRegion,AddressLocality,AddressCountry,Tags,File_Type
0,Bramble Rock,http://www.bramblerock.com,+353(0)40445075,-6.291733,53.009756,Wicklow,Glendalough,Republic of Ireland,B&B,Accom.
1,The Davenport,http://www.instagram.com/thedavenportdublin/,+353(0)16073500,-6.250031,53.341665,Dublin,Dublin City,Republic of Ireland,"Hotel,Covid Safety Charter",Accom.
2,Townsend House,http://www.townsendhouse-guesthouse.com,+353(0)579121276,-7.909500,53.098816,Offaly,Birr,Republic of Ireland,"Guesthouse,Covid Safety Charter",Accom.
3,River's Edge,http://www.riversedge.ie,3.5367E+11,-9.783882,52.106485,Kerry,Killorglin,Ireland,"B&B,B&B Ireland",Accom.
4,Amber Springs Hotel & Health Spa,https://www.ambersprings.ie/,+353(0)539484000,-6.290339,52.668124,Wexford,Gorey,Republic of Ireland,"Hotel,Covid Safety Charter,Stay and Spend",Accom.
...,...,...,...,...,...,...,...,...,...,...
6313,The Marine Bar,http://marinebar.ie,+35358462520,-7.659723,52.041345,Waterford,Ring,Republic of Ireland,"Food and Drink,Restaurant,Pubs and Bar",Act.
6314,The West End Cliff Walk,NaN,+353(0)749121160,-8.274541,54.479625,Donegal,Bundoran,Republic of Ireland,Walking,Act.
6315,The Workhouse Famine & Heritage Centre,http://www.dunfanaghy.info/places/The-Workhous...,+353749136540,-7.976993,55.179878,Donegal,Dunfanaghy,Republic of Ireland,"Museums and Attraction,Cafe,Food and Drink",Act.
6316,Walking Hiking Tours - JAQUIER Lilian,https://www.facebook.com/pages/Escapades-natur...,+353(0)857481764,-10.021117,53.489293,Galway,Clifden,Republic of Ireland,"Walking,Activity Operator,Tour",Act.
6317,Youghal Clock Gate Tower,https://youghalclockgate.ie,+3532420769,-7.846767,51.952759,Cork,Youghal,Republic of Ireland,"Covid Safety Charter,Historic Houses and Castl...",Act.

In [12]:
Ireland = pd.concat([Accommodation, Activities], axis = 0)

In [13]:
Ireland.head()

,Name,Url,Telephone,Longitude,Latitude,AddressRegion,AddressLocality,AddressCountry,Tags,File_Type
0,Bramble Rock,http://www.bramblerock.com,+353(0)40445075,-6.291733,53.009756,Wicklow,Glendalough,Republic of Ireland,B&B,Accom.
1,The Davenport,http://www.instagram.com/thedavenportdublin/,+353(0)16073500,-6.250031,53.341665,Dublin,Dublin City,Republic of Ireland,"Hotel,Covid Safety Charter",Accom.
2,Townsend House,http://www.townsendhouse-guesthouse.com,+353(0)579121276,-7.909500,53.098816,Offaly,Birr,Republic of Ireland,"Guesthouse,Covid Safety Charter",Accom.
3,River's Edge,http://www.riversedge.ie,3.5367E+11,-9.783882,52.106485,Kerry,Killorglin,Ireland,"B&B,B&B Ireland",Accom.
4,Amber Springs Hotel & Health Spa,https://www.ambersprings.ie/,+353(0)539484000,-6.290339,52.668124,Wexford,Gorey,Republic of Ireland,"Hotel,Covid Safety Charter,Stay and Spend",Accom.

In [14]:
Ireland.columns = Ireland.columns.str.replace("AddressRegion" , "County")
Ireland.head()

,Name,Url,Telephone,Longitude,Latitude,County,AddressLocality,AddressCountry,Tags,File_Type
0,Bramble Rock,http://www.bramblerock.com,+353(0)40445075,-6.291733,53.009756,Wicklow,Glendalough,Republic of Ireland,B&B,Accom.
1,The Davenport,http://www.instagram.com/thedavenportdublin/,+353(0)16073500,-6.250031,53.341665,Dublin,Dublin City,Republic of Ireland,"Hotel,Covid Safety Charter",Accom.
2,Townsend House,http://www.townsendhouse-guesthouse.com,+353(0)579121276,-7.909500,53.098816,Offaly,Birr,Republic of Ireland,"Guesthouse,Covid Safety Charter",Accom.
3,River's Edge,http://www.riversedge.ie,3.5367E+11,-9.783882,52.106485,Kerry,Killorglin,Ireland,"B&B,B&B Ireland",Accom.
4,Amber Springs Hotel & Health Spa,https://www.ambersprings.ie/,+353(0)539484000,-6.290339,52.668124,Wexford,Gorey,Republic of Ireland,"Hotel,Covid Safety Charter,Stay and Spend",Accom.

In [15]:
Ireland.drop(['Url', 'Telephone','AddressLocality', 'AddressCountry'], axis=1)
Ire = Ireland.drop(['Url', 'Telephone','AddressLocality', 'AddressCountry'], axis=1)
print(Ire)

                                        Name  Longitude   Latitude     County  \
0                               Bramble Rock  -6.291733  53.009756    Wicklow
1                              The Davenport  -6.250031  53.341665     Dublin
2                             Townsend House  -7.909500  53.098816     Offaly
3                               River's Edge  -9.783882  52.106485      Kerry
4           Amber Springs Hotel & Health Spa  -6.290339  52.668124    Wexford
...                                      ...        ...        ...        ...
6313                          The Marine Bar  -7.659723  52.041345  Waterford
6314                 The West End Cliff Walk  -8.274541  54.479625    Donegal
6315  The Workhouse Famine & Heritage Centre  -7.976993  55.179878    Donegal
6316   Walking Hiking Tours - JAQUIER Lilian -10.021117  53.489293     Galway
6317                Youghal Clock Gate Tower  -7.846767  51.952759       Cork

                                                   Tags File_Type
0                                                   B&B    Accom.
1                            Hotel,Covid Safety Charter    Accom.
2                       Guesthouse,Covid Safety Charter    Accom.
3                                       B&B,B&B Ireland    Accom.
4             Hotel,Covid Safety Charter,Stay and Spend    Accom.
...                                                 ...       ...
6313             Food and Drink,Restaurant,Pubs and Bar      Act.
6314                                            Walking      Act.
6315         Museums and Attraction,Cafe,Food and Drink      Act.
6316                     Walking,Activity Operator,Tour      Act.
6317  Covid Safety Charter,Historic Houses and Castl...      Act.

[9091 rows x 6 columns]

In [16]:
Ire.isnull().sum()

Name          0
Longitude     0
Latitude      0
County        4
Tags         82
File_Type     0
dtype: int64

In [17]:
Ire[Ire['County'].isnull()]

,Name,Longitude,Latitude,County,Tags,File_Type
291,The Elm Tree,-8.304398,51.911999,NaN,"Covid Safety Charter,Food and Drink,Restaurant...",Act.
1687,Knoxs Pub & Restaurant,-8.982425,52.844943,NaN,"Food and Drink,Restaurant,Pubs and Bar",Act.
2229,The Roundwood Inn,-6.224734,53.064770,NaN,"Food and Drink,Restaurant,Seafood,Vegetarian",Act.
3068,Toddies at the Bulman,-8.499729,51.700103,NaN,"Food and Drink,Restaurant",Act.

In [18]:
Ire.loc[Ire["Name"] == "The Elm Tree" , "County"] = 'Cork'
Ire.loc[Ire["Name"] == "Knoxs Pub & Restaurant" , "County"] = 'Clare'
Ire.loc[Ire["Name"] == "The Roundwood Inn" , "County"] = 'Wicklow'
Ire.loc[Ire["Name"] == "Toddies at the Bulman" , "County"] = 'Cork'

In [19]:
Ire[Ire['County'].isnull()]

Empty DataFrame
Columns: [Name, Longitude, Latitude, County, Tags, File_Type]
Index: []

In [20]:
Ire[Ire['Tags'].isnull()]

,Name,Longitude,Latitude,County,Tags,File_Type
47,Staigue Fort,-10.038945,51.780516,Kerry,NaN,Act.
80,The Ha'Penny Laugh,-6.263344,53.345871,Dublin,NaN,Act.
161,Haroldstown Dolmen,-6.663829,52.845101,Carlow,NaN,Act.
215,Ballynamona Court Cairn,-7.581712,52.003606,Waterford,NaN,Act.
237,Explore Louth Heritage Trail,-6.405957,53.997945,Louth,NaN,Act.
...,...,...,...,...,...,...
5752,Arthur's Quay Park,-8.626228,52.665374,Limerick,NaN,Act.
5825,Mullaghmast,-6.848484,53.006619,Kildare,NaN,Act.
5863,Westport Skate Park & Multi-use Games Area,-9.529272,53.795305,Mayo,NaN,Act.
5911,Dean Crowe Theatre,-7.943734,53.421923,Westmeath,NaN,Act.
5980,The Pollock Holes,-9.664980,52.682283,Clare,NaN,Act.

In [21]:
Ire.dropna(axis = 0, how = 'any', inplace = True)

In [22]:
Ire[Ire['Tags'].isnull()]

Empty DataFrame
Columns: [Name, Longitude, Latitude, County, Tags, File_Type]
Index: []

In [23]:
print(Ire)

                                        Name  Longitude   Latitude     County  \
0                               Bramble Rock  -6.291733  53.009756    Wicklow
1                              The Davenport  -6.250031  53.341665     Dublin
2                             Townsend House  -7.909500  53.098816     Offaly
3                               River's Edge  -9.783882  52.106485      Kerry
4           Amber Springs Hotel & Health Spa  -6.290339  52.668124    Wexford
...                                      ...        ...        ...        ...
6313                          The Marine Bar  -7.659723  52.041345  Waterford
6314                 The West End Cliff Walk  -8.274541  54.479625    Donegal
6315  The Workhouse Famine & Heritage Centre  -7.976993  55.179878    Donegal
6316   Walking Hiking Tours - JAQUIER Lilian -10.021117  53.489293     Galway
6317                Youghal Clock Gate Tower  -7.846767  51.952759       Cork

                                                   Tags File_Type
0                                                   B&B    Accom.
1                            Hotel,Covid Safety Charter    Accom.
2                       Guesthouse,Covid Safety Charter    Accom.
3                                       B&B,B&B Ireland    Accom.
4             Hotel,Covid Safety Charter,Stay and Spend    Accom.
...                                                 ...       ...
6313             Food and Drink,Restaurant,Pubs and Bar      Act.
6314                                            Walking      Act.
6315         Museums and Attraction,Cafe,Food and Drink      Act.
6316                     Walking,Activity Operator,Tour      Act.
6317  Covid Safety Charter,Historic Houses and Castl...      Act.

[9009 rows x 6 columns]

In [24]:
#multiple listed categories are in single row which is not good and that effect our analysis try to correct them

In [25]:
Ire["Tags"].value_counts().head(30)

B&B,Covid Safety Charter                                                               450
Hotel,Covid Safety Charter                                                             392
Food and Drink,Restaurant                                                              330
Food and Drink,Restaurant,Pubs and Bar                                                 309
Activity Operator,Tour                                                                 306
B&B                                                                                    288
Hotel,Covid Safety Charter,Stay and Spend                                              287
Walking                                                                                184
Self Catering Accommodation                                                            178
Craft,Shopping,Shopping Centres and Department Store,Food Shops                        163
Covid Safety Charter,Food and Drink,Restaurant,Pubs and Bar                            152
Golf Course,Golf,Activity Operator                                                     152
Walking,Activity Operator,Tour                                                         133
Self Catering Accommodation,Covid Safety Charter                                       127
Shopping,Shopping Centres and Department Store,Food Shops                              126
Self Catering Accommodation,Welcome Standard                                           113
Food and Drink,Restaurant,Cafe                                                         109
Food and Drink,Restaurant,Shopping,Shopping Centres and Department Store,Food Shops    106
Hotel                                                                                  100
Transport,Coach,Road                                                                    93
Fishing,Angling                                                                         79
Covid Safety Charter,Food and Drink,Restaurant                                          79
B&B,Welcome Standard                                                                    77
B&B,B&B Ireland,Covid Safety Charter                                                    70
Walking,Natural Landscape                                                               69
B&B,Covid Safety Charter,Welcome Standard                                               64
Activity Operator                                                                       63
Discovery Point                                                                         60
Guesthouse,Covid Safety Charter                                                         58
Golf Course,Golf,Driving Range,General,Golf Driving Range,Activity Operator             56
Name: Tags, dtype: int64